// This JLex file was machine-generated by the BNF converter
package CPP;
import java_cup.runtime.*;


public class Yylex implements java_cup.runtime.Scanner {
	private final int YY_BUFFER_SIZE = 512;
	private final int YY_F = -1;
	private final int YY_NO_STATE = -1;
	private final int YY_NOT_ACCEPT = 0;
	private final int YY_START = 1;
	private final int YY_END = 2;
	private final int YY_NO_ANCHOR = 4;
	private final int YY_BOL = 65536;
	private final int YY_EOF = 65537;

  String pstring = new String();
  public int line_num() { return (yyline+1); }
  public String buff() {return new String(yy_buffer,yy_buffer_index,10).trim();}
	private java.io.BufferedReader yy_reader;
	private int yy_buffer_index;
	private int yy_buffer_read;
	private int yy_buffer_start;
	private int yy_buffer_end;
	private char yy_buffer[];
	private int yyline;
	private boolean yy_at_bol;
	private int yy_lexical_state;

	public Yylex (java.io.Reader reader) {
		this ();
		if (null == reader) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(reader);
	}

	public Yylex (java.io.InputStream instream) {
		this ();
		if (null == instream) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(new java.io.InputStreamReader(instream));
	}

	private Yylex () {
		yy_buffer = new char[YY_BUFFER_SIZE];
		yy_buffer_read = 0;
		yy_buffer_index = 0;
		yy_buffer_start = 0;
		yy_buffer_end = 0;
		yyline = 0;
		yy_at_bol = true;
		yy_lexical_state = YYINITIAL;
	}

	private boolean yy_eof_done = false;
	private final int STRING = 5;
	private final int ESCAPED = 6;
	private final int YYINITIAL = 0;
	private final int COMMENT = 1;
	private final int CHAREND = 4;
	private final int CHARESC = 3;
	private final int CHAR = 2;
	private final int yy_state_dtrans[] = {
		0,
		67,
		68,
		68,
		68,
		69,
		70
	};
	private void yybegin (int state) {
		yy_lexical_state = state;
	}
	private int yy_advance ()
		throws java.io.IOException {
		int next_read;
		int i;
		int j;

		if (yy_buffer_index < yy_buffer_read) {
			return yy_buffer[yy_buffer_index++];
		}

		if (0 != yy_buffer_start) {
			i = yy_buffer_start;
			j = 0;
			while (i < yy_buffer_read) {
				yy_buffer[j] = yy_buffer[i];
				++i;
				++j;
			}
			yy_buffer_end = yy_buffer_end - yy_buffer_start;
			yy_buffer_start = 0;
			yy_buffer_read = j;
			yy_buffer_index = j;
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}

		while (yy_buffer_index >= yy_buffer_read) {
			if (yy_buffer_index >= yy_buffer.length) {
				yy_buffer = yy_double(yy_buffer);
			}
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}
		return yy_buffer[yy_buffer_index++];
	}
	private void yy_move_end () {
		if (yy_buffer_end > yy_buffer_start &&
		    '\n' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
		if (yy_buffer_end > yy_buffer_start &&
		    '\r' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
	}
	private boolean yy_last_was_cr=false;
	private void yy_mark_start () {
		int i;
		for (i = yy_buffer_start; i < yy_buffer_index; ++i) {
			if ('\n' == yy_buffer[i] && !yy_last_was_cr) {
				++yyline;
			}
			if ('\r' == yy_buffer[i]) {
				++yyline;
				yy_last_was_cr=true;
			} else yy_last_was_cr=false;
		}
		yy_buffer_start = yy_buffer_index;
	}
	private void yy_mark_end () {
		yy_buffer_end = yy_buffer_index;
	}
	private void yy_to_mark () {
		yy_buffer_index = yy_buffer_end;
		yy_at_bol = (yy_buffer_end > yy_buffer_start) &&
		            ('\r' == yy_buffer[yy_buffer_end-1] ||
		             '\n' == yy_buffer[yy_buffer_end-1] ||
		             2028/*LS*/ == yy_buffer[yy_buffer_end-1] ||
		             2029/*PS*/ == yy_buffer[yy_buffer_end-1]);
	}
	private java.lang.String yytext () {
		return (new java.lang.String(yy_buffer,
			yy_buffer_start,
			yy_buffer_end - yy_buffer_start));
	}
	private int yylength () {
		return yy_buffer_end - yy_buffer_start;
	}
	private char[] yy_double (char buf[]) {
		int i;
		char newbuf[];
		newbuf = new char[2*buf.length];
		for (i = 0; i < buf.length; ++i) {
			newbuf[i] = buf[i];
		}
		return newbuf;
	}
	private final int YY_E_INTERNAL = 0;
	private final int YY_E_MATCH = 1;
	private java.lang.String yy_error_string[] = {
		"Error: Internal error.\n",
		"Error: Unmatched input.\n"
	};
	private void yy_error (int code,boolean fatal) {
		java.lang.System.out.print(yy_error_string[code]);
		java.lang.System.out.flush();
		if (fatal) {
			throw new Error("Fatal Error.\n");
		}
	}
	private int[][] unpackFromString(int size1, int size2, String st) {
		int colonIndex = -1;
		String lengthString;
		int sequenceLength = 0;
		int sequenceInteger = 0;

		int commaIndex;
		String workString;

		int res[][] = new int[size1][size2];
		for (int i= 0; i < size1; i++) {
			for (int j= 0; j < size2; j++) {
				if (sequenceLength != 0) {
					res[i][j] = sequenceInteger;
					sequenceLength--;
					continue;
				}
				commaIndex = st.indexOf(',');
				workString = (commaIndex==-1) ? st :
					st.substring(0, commaIndex);
				st = st.substring(commaIndex+1);
				colonIndex = workString.indexOf(':');
				if (colonIndex == -1) {
					res[i][j]=Integer.parseInt(workString);
					continue;
				}
				lengthString =
					workString.substring(colonIndex+1);
				sequenceLength=Integer.parseInt(lengthString);
				workString=workString.substring(0,colonIndex);
				sequenceInteger=Integer.parseInt(workString);
				res[i][j] = sequenceInteger;
				sequenceLength--;
			}
		}
		return res;
	}
	private int yy_acpt[] = {
		/* 0 */ YY_NOT_ACCEPT,
		/* 1 */ YY_NO_ANCHOR,
		/* 2 */ YY_NO_ANCHOR,
		/* 3 */ YY_NO_ANCHOR,
		/* 4 */ YY_NO_ANCHOR,
		/* 5 */ YY_NO_ANCHOR,
		/* 6 */ YY_NO_ANCHOR,
		/* 7 */ YY_NO_ANCHOR,
		/* 8 */ YY_NO_ANCHOR,
		/* 9 */ YY_NO_ANCHOR,
		/* 10 */ YY_NO_ANCHOR,
		/* 11 */ YY_NO_ANCHOR,
		/* 12 */ YY_NO_ANCHOR,
		/* 13 */ YY_NO_ANCHOR,
		/* 14 */ YY_NO_ANCHOR,
		/* 15 */ YY_NO_ANCHOR,
		/* 16 */ YY_NO_ANCHOR,
		/* 17 */ YY_NO_ANCHOR,
		/* 18 */ YY_NO_ANCHOR,
		/* 19 */ YY_NO_ANCHOR,
		/* 20 */ YY_NO_ANCHOR,
		/* 21 */ YY_NO_ANCHOR,
		/* 22 */ YY_NO_ANCHOR,
		/* 23 */ YY_NO_ANCHOR,
		/* 24 */ YY_NO_ANCHOR,
		/* 25 */ YY_NO_ANCHOR,
		/* 26 */ YY_NO_ANCHOR,
		/* 27 */ YY_NO_ANCHOR,
		/* 28 */ YY_NO_ANCHOR,
		/* 29 */ YY_NO_ANCHOR,
		/* 30 */ YY_NO_ANCHOR,
		/* 31 */ YY_NO_ANCHOR,
		/* 32 */ YY_NO_ANCHOR,
		/* 33 */ YY_NO_ANCHOR,
		/* 34 */ YY_NO_ANCHOR,
		/* 35 */ YY_NO_ANCHOR,
		/* 36 */ YY_NO_ANCHOR,
		/* 37 */ YY_NO_ANCHOR,
		/* 38 */ YY_NO_ANCHOR,
		/* 39 */ YY_NO_ANCHOR,
		/* 40 */ YY_NO_ANCHOR,
		/* 41 */ YY_NO_ANCHOR,
		/* 42 */ YY_NO_ANCHOR,
		/* 43 */ YY_NO_ANCHOR,
		/* 44 */ YY_NO_ANCHOR,
		/* 45 */ YY_NOT_ACCEPT,
		/* 46 */ YY_NO_ANCHOR,
		/* 47 */ YY_NO_ANCHOR,
		/* 48 */ YY_NO_ANCHOR,
		/* 49 */ YY_NOT_ACCEPT,
		/* 50 */ YY_NO_ANCHOR,
		/* 51 */ YY_NOT_ACCEPT,
		/* 52 */ YY_NO_ANCHOR,
		/* 53 */ YY_NOT_ACCEPT,
		/* 54 */ YY_NO_ANCHOR,
		/* 55 */ YY_NOT_ACCEPT,
		/* 56 */ YY_NO_ANCHOR,
		/* 57 */ YY_NOT_ACCEPT,
		/* 58 */ YY_NO_ANCHOR,
		/* 59 */ YY_NOT_ACCEPT,
		/* 60 */ YY_NO_ANCHOR,
		/* 61 */ YY_NOT_ACCEPT,
		/* 62 */ YY_NO_ANCHOR,
		/* 63 */ YY_NOT_ACCEPT,
		/* 64 */ YY_NO_ANCHOR,
		/* 65 */ YY_NOT_ACCEPT,
		/* 66 */ YY_NO_ANCHOR,
		/* 67 */ YY_NOT_ACCEPT,
		/* 68 */ YY_NOT_ACCEPT,
		/* 69 */ YY_NOT_ACCEPT,
		/* 70 */ YY_NOT_ACCEPT,
		/* 71 */ YY_NO_ANCHOR,
		/* 72 */ YY_NO_ANCHOR,
		/* 73 */ YY_NO_ANCHOR,
		/* 74 */ YY_NO_ANCHOR,
		/* 75 */ YY_NO_ANCHOR,
		/* 76 */ YY_NO_ANCHOR,
		/* 77 */ YY_NO_ANCHOR,
		/* 78 */ YY_NO_ANCHOR,
		/* 79 */ YY_NO_ANCHOR,
		/* 80 */ YY_NO_ANCHOR,
		/* 81 */ YY_NO_ANCHOR,
		/* 82 */ YY_NO_ANCHOR,
		/* 83 */ YY_NO_ANCHOR,
		/* 84 */ YY_NO_ANCHOR,
		/* 85 */ YY_NO_ANCHOR,
		/* 86 */ YY_NO_ANCHOR,
		/* 87 */ YY_NO_ANCHOR,
		/* 88 */ YY_NO_ANCHOR,
		/* 89 */ YY_NO_ANCHOR,
		/* 90 */ YY_NO_ANCHOR,
		/* 91 */ YY_NO_ANCHOR,
		/* 92 */ YY_NO_ANCHOR,
		/* 93 */ YY_NO_ANCHOR,
		/* 94 */ YY_NO_ANCHOR,
		/* 95 */ YY_NO_ANCHOR,
		/* 96 */ YY_NO_ANCHOR
	};
	private int yy_cmap[] = unpackFromString(1,65538,
"38:9,45,35,38,45,34,38:18,45,38,43,33,38:4,1,2,37,38,5,11,10,36,41:10,14,6," +
"13,7,12,38:2,39:26,8,44,9,38,42,38,40,15,40,18,20,23,29,32,22,40:2,17,40,24" +
",16,28,40,26,21,25,19,30,31,40,27,40,3,38,4,38:66,39:23,38,39:7,40:24,38,40" +
":8,38:65280,0:2")[0];

	private int yy_rmap[] = unpackFromString(1,97,
"0,1:11,2,1,3,1:5,4,1:2,4,1,5,4:8,1:11,6,7,8,9,10,11,12,13,14,15,16,17,18,19" +
",20,21,22,23,24,25,8,26,27,28,29,30,31,4,32,33,34,35,36,37,38,39,40,41,42,4" +
"3,44,45,46,4,47,48,49,50,51,52,53,54")[0];

	private int yy_nxt[][] = unpackFromString(55,46,
"1,2,3,4,5,6,7,8,9,10,11,45,49,51,53,12,88:2,90,91,92,88,46,88:2,93,94,88:3," +
"95,96,88,55,13:2,57,-1:2,88:2,14,-1,15,-1,13,-1:61,88,71,88:16,-1:6,72,88,7" +
"2:2,-1:13,61,-1:30,14,-1:19,88:18,-1:6,72,88,72:2,-1:23,63,-1:20,25,-1:16,1" +
"6,-1:48,88:8,20,50,88:8,-1:6,72,88,72:2,-1:44,47,-1:40,36,-1:21,17,-1:48,88" +
":10,23,88:7,-1:6,72,88,72:2,-1:16,18,-1:47,88:2,26,88:15,-1:6,72,88,72:2,-1" +
":17,19,-1:46,88:5,27,88:12,-1:6,72,88,72:2,-1:4,55:34,21,55:10,-1:15,88:3,2" +
"8,88:14,-1:6,72,88,72:2,-1:39,59,22,-1:23,88:14,29,88:3,-1:6,72,88,72:2,-1:" +
"4,59:34,24,59:10,-1:15,88:5,30,88:12,-1:6,72,88,72:2,-1:44,25,-1:19,88:5,31" +
",88:12,-1:6,72,88,72:2,-1:14,65,-1:29,47,-1:19,88:9,32,88:8,-1:6,72,88,72:2" +
",-1:18,88:8,33,88:9,-1:6,72,88,72:2,-1:3,1,34:33,-1,35,34,48,34:8,1,-1:45,1" +
",37:33,-1:2,37:7,38,39,37,1,40:23,41,42,40:8,-1:2,40:7,43,44,40,-1:15,88,52" +
",88:16,-1:6,72,88,72:2,-1:18,88:4,79,88:13,-1:6,72,88,72:2,-1:18,88:7,80,88" +
":10,-1:6,72,88,72:2,-1:18,88:6,54,88:11,-1:6,72,88,72:2,-1:18,88:13,81,88:4" +
",-1:6,72,88,72:2,-1:18,88:10,82,88:7,-1:6,72,88,72:2,-1:18,88:7,56,88:10,-1" +
":6,72,88,72:2,-1:18,84,88:17,-1:6,72,88,72:2,-1:18,88:9,58,88:8,-1:6,72,88," +
"72:2,-1:18,88:5,85,88:12,-1:6,72,88,72:2,-1:18,88:4,86,88:13,-1:6,72,88,72:" +
"2,-1:18,88:2,60,88:15,-1:6,72,88,72:2,-1:18,88:2,62,88:15,-1:6,72,88,72:2,-" +
"1:18,88:3,87,88:14,-1:6,72,88,72:2,-1:18,88:11,64,88:6,-1:6,72,88,72:2,-1:1" +
"8,88:5,66,88:12,-1:6,72,88,72:2,-1:18,88:7,83,88:10,-1:6,72,88,72:2,-1:18,8" +
"8,73,88:16,-1:6,72,88,72:2,-1:18,88:6,74,88:11,-1:6,72,88,72:2,-1:18,88:2,7" +
"5,88:15,-1:6,72,88,72:2,-1:18,88:12,76,88:5,-1:6,72,88,72:2,-1:18,88:5,77,8" +
"8:12,-1:6,72,88,72:2,-1:18,88,78,88:16,-1:6,72,88,72:2,-1:18,88:17,89,-1:6," +
"72,88,72:2,-1:3");

	public java_cup.runtime.Symbol next_token ()
		throws java.io.IOException {
		int yy_lookahead;
		int yy_anchor = YY_NO_ANCHOR;
		int yy_state = yy_state_dtrans[yy_lexical_state];
		int yy_next_state = YY_NO_STATE;
		int yy_last_accept_state = YY_NO_STATE;
		boolean yy_initial = true;
		int yy_this_accept;

		yy_mark_start();
		yy_this_accept = yy_acpt[yy_state];
		if (YY_NOT_ACCEPT != yy_this_accept) {
			yy_last_accept_state = yy_state;
			yy_mark_end();
		}
		while (true) {
			if (yy_initial && yy_at_bol) yy_lookahead = YY_BOL;
			else yy_lookahead = yy_advance();
			yy_next_state = YY_F;
			yy_next_state = yy_nxt[yy_rmap[yy_state]][yy_cmap[yy_lookahead]];
			if (YY_EOF == yy_lookahead && true == yy_initial) {
				return null;
			}
			if (YY_F != yy_next_state) {
				yy_state = yy_next_state;
				yy_initial = false;
				yy_this_accept = yy_acpt[yy_state];
				if (YY_NOT_ACCEPT != yy_this_accept) {
					yy_last_accept_state = yy_state;
					yy_mark_end();
				}
			}
			else {
				if (YY_NO_STATE == yy_last_accept_state) {
					throw (new Error("Lexical Error: Unmatched Input."));
				}
				else {
					yy_anchor = yy_acpt[yy_last_accept_state];
					if (0 != (YY_END & yy_anchor)) {
						yy_move_end();
					}
					yy_to_mark();
					switch (yy_last_accept_state) {
					case 1:
						
					case -2:
						break;
					case 2:
						{ return new Symbol(sym._SYMB_0); }
					case -3:
						break;
					case 3:
						{ return new Symbol(sym._SYMB_1); }
					case -4:
						break;
					case 4:
						{ return new Symbol(sym._SYMB_2); }
					case -5:
						break;
					case 5:
						{ return new Symbol(sym._SYMB_3); }
					case -6:
						break;
					case 6:
						{ return new Symbol(sym._SYMB_4); }
					case -7:
						break;
					case 7:
						{ return new Symbol(sym._SYMB_5); }
					case -8:
						break;
					case 8:
						{ return new Symbol(sym._SYMB_6); }
					case -9:
						break;
					case 9:
						{ return new Symbol(sym._SYMB_7); }
					case -10:
						break;
					case 10:
						{ return new Symbol(sym._SYMB_8); }
					case -11:
						break;
					case 11:
						{ return new Symbol(sym._SYMB_9); }
					case -12:
						break;
					case 12:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -13:
						break;
					case 13:
						{ /* ignore white space. */ }
					case -14:
						break;
					case 14:
						{ return new Symbol(sym._INTEGER_, new Integer(yytext())); }
					case -15:
						break;
					case 15:
						{ yybegin(STRING); }
					case -16:
						break;
					case 16:
						{ return new Symbol(sym._SYMB_10); }
					case -17:
						break;
					case 17:
						{ return new Symbol(sym._SYMB_12); }
					case -18:
						break;
					case 18:
						{ return new Symbol(sym._SYMB_11); }
					case -19:
						break;
					case 19:
						{ return new Symbol(sym._SYMB_13); }
					case -20:
						break;
					case 20:
						{ return new Symbol(sym._SYMB_17); }
					case -21:
						break;
					case 21:
						{ /* skip */ }
					case -22:
						break;
					case 22:
						{ yybegin(COMMENT); }
					case -23:
						break;
					case 23:
						{ return new Symbol(sym._SYMB_18); }
					case -24:
						break;
					case 24:
						{ /* skip */ }
					case -25:
						break;
					case 25:
						{ return new Symbol(sym._DOUBLE_, new Double(yytext())); }
					case -26:
						break;
					case 26:
						{ return new Symbol(sym._SYMB_14); }
					case -27:
						break;
					case 27:
						{ return new Symbol(sym._SYMB_16); }
					case -28:
						break;
					case 28:
						{ return new Symbol(sym._SYMB_22); }
					case -29:
						break;
					case 29:
						{ return new Symbol(sym._SYMB_21); }
					case -30:
						break;
					case 30:
						{ return new Symbol(sym._SYMB_23); }
					case -31:
						break;
					case 31:
						{ return new Symbol(sym._SYMB_15); }
					case -32:
						break;
					case 32:
						{ return new Symbol(sym._SYMB_19); }
					case -33:
						break;
					case 33:
						{ return new Symbol(sym._SYMB_20); }
					case -34:
						break;
					case 34:
						{ /* skip */ }
					case -35:
						break;
					case 35:
						{ /* skip */ }
					case -36:
						break;
					case 36:
						{ yybegin(YYINITIAL); }
					case -37:
						break;
					case 37:
						{ pstring += yytext(); }
					case -38:
						break;
					case 38:
						{ String foo = pstring; pstring = new String(); yybegin(YYINITIAL); return new Symbol(sym._STRING_, foo.intern()); }
					case -39:
						break;
					case 39:
						{ yybegin(ESCAPED); }
					case -40:
						break;
					case 40:
						{ pstring += yytext(); yybegin(STRING); }
					case -41:
						break;
					case 41:
						{ pstring +=  "\n"; yybegin(STRING); }
					case -42:
						break;
					case 42:
						{ pstring += "\t"; yybegin(STRING); }
					case -43:
						break;
					case 43:
						{ pstring += "\""; yybegin(STRING); }
					case -44:
						break;
					case 44:
						{ pstring += "\\"; yybegin(STRING); }
					case -45:
						break;
					case 46:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -46:
						break;
					case 47:
						{ return new Symbol(sym._DOUBLE_, new Double(yytext())); }
					case -47:
						break;
					case 48:
						{ /* skip */ }
					case -48:
						break;
					case 50:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -49:
						break;
					case 52:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -50:
						break;
					case 54:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -51:
						break;
					case 56:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -52:
						break;
					case 58:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -53:
						break;
					case 60:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -54:
						break;
					case 62:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -55:
						break;
					case 64:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -56:
						break;
					case 66:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -57:
						break;
					case 71:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -58:
						break;
					case 72:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -59:
						break;
					case 73:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -60:
						break;
					case 74:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -61:
						break;
					case 75:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -62:
						break;
					case 76:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -63:
						break;
					case 77:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -64:
						break;
					case 78:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -65:
						break;
					case 79:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -66:
						break;
					case 80:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -67:
						break;
					case 81:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -68:
						break;
					case 82:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -69:
						break;
					case 83:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -70:
						break;
					case 84:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -71:
						break;
					case 85:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -72:
						break;
					case 86:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -73:
						break;
					case 87:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -74:
						break;
					case 88:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -75:
						break;
					case 89:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -76:
						break;
					case 90:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -77:
						break;
					case 91:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -78:
						break;
					case 92:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -79:
						break;
					case 93:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -80:
						break;
					case 94:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -81:
						break;
					case 95:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -82:
						break;
					case 96:
						{ return new Symbol(sym.Id, yytext().intern()); }
					case -83:
						break;
					default:
						yy_error(YY_E_INTERNAL,false);
					case -1:
					}
					yy_initial = true;
					yy_state = yy_state_dtrans[yy_lexical_state];
					yy_next_state = YY_NO_STATE;
					yy_last_accept_state = YY_NO_STATE;
					yy_mark_start();
					yy_this_accept = yy_acpt[yy_state];
					if (YY_NOT_ACCEPT != yy_this_accept) {
						yy_last_accept_state = yy_state;
						yy_mark_end();
					}
				}
			}
		}
	}
}
