

module AbsCPP where

-- Haskell module generated by the BNF converter




newtype Id = Id String deriving (Eq, Ord, Show, Read)
data Program = Prog [Def]
  deriving (Eq, Ord, Show, Read)

data Def = DFun Type Id [Arg] [Stm] | QConuse [Id]
  deriving (Eq, Ord, Show, Read)

data Arg = ADecl Type Id
  deriving (Eq, Ord, Show, Read)

data Stm
    = SExp Exp
    | SDecl Type Id
    | SDecls Type Id [Id]
    | SInit Type Id Exp
    | STypedef [Id] Id
    | SReturn Exp
    | SWhile Exp Stm
    | SBlock [Stm]
    | SIfElse Exp Stm Stm
  deriving (Eq, Ord, Show, Read)

data Exp
    = EInt Integer
    | EString [String]
    | EDouble Double
    | EQcon [Id]
    | EIndex Exp Exp
    | ECall Exp [Exp]
    | ECalle Exp
    | EDot Exp Exp
    | EArrow Exp Id
    | EInc Exp
    | EDec Exp
    | EPinc Exp
    | EPdec Exp
    | EDeref Exp
    | ENeg Exp
    | EMul Exp Exp
    | EDiv Exp Exp
    | EMod Exp Exp
    | EAdd Exp Exp
    | ESub Exp Exp
    | ELShift Exp Exp
    | ERShift Exp Exp
    | EEq Exp Exp
    | ENeq Exp Exp
    | EConj Exp Exp
    | EDisj Exp Exp
    | EAss Exp Exp
    | EAssp Exp Exp
    | EAssm Exp Exp
    | ECond Exp Exp Exp
  deriving (Eq, Ord, Show, Read)

data Type = Tbool | Tdouble | Tint | Tvoid | Tid [Id]
  deriving (Eq, Ord, Show, Read)

