package CPP.Absyn; // Java Package generated by the BNF Converter.

public class Dec extends Decl {
  public final Type type_;
  public final ListIdent listident_;
  public Dec(Type p1, ListIdent p2) { type_ = p1; listident_ = p2; }

  public <R,A> R accept(CPP.Absyn.Decl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof CPP.Absyn.Dec) {
      CPP.Absyn.Dec x = (CPP.Absyn.Dec)o;
      return this.type_.equals(x.type_) && this.listident_.equals(x.listident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.type_.hashCode())+this.listident_.hashCode();
  }


}
