package CPP.Absyn; // Java Package generated by the BNF Converter.

public class DVardeq extends Def {
  public final ListTypen listtypen_;
  public DVardeq(ListTypen p1) { listtypen_ = p1; }

  public <R,A> R accept(CPP.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof CPP.Absyn.DVardeq) {
      CPP.Absyn.DVardeq x = (CPP.Absyn.DVardeq)o;
      return this.listtypen_.equals(x.listtypen_);
    }
    return false;
  }

  public int hashCode() {
    return this.listtypen_.hashCode();
  }


}
