package CPP.Absyn; // Java Package generated by the BNF Converter.

public class EName extends Exp {
  public final ListName listname_;
  public EName(ListName p1) { listname_ = p1; }

  public <R,A> R accept(CPP.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof CPP.Absyn.EName) {
      CPP.Absyn.EName x = (CPP.Absyn.EName)o;
      return this.listname_.equals(x.listname_);
    }
    return false;
  }

  public int hashCode() {
    return this.listname_.hashCode();
  }


}
