package CPP.Absyn; // Java Package generated by the BNF Converter.

public class Fun extends Function {
  public final Type type_;
  public final String ident_;
  public final ListDecl listdecl_;
  public final ListStm liststm_;
  public Fun(Type p1, String p2, ListDecl p3, ListStm p4) { type_ = p1; ident_ = p2; listdecl_ = p3; liststm_ = p4; }

  public <R,A> R accept(CPP.Absyn.Function.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof CPP.Absyn.Fun) {
      CPP.Absyn.Fun x = (CPP.Absyn.Fun)o;
      return this.type_.equals(x.type_) && this.ident_.equals(x.ident_) && this.listdecl_.equals(x.listdecl_) && this.liststm_.equals(x.liststm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.type_.hashCode())+this.ident_.hashCode())+this.listdecl_.hashCode())+this.liststm_.hashCode();
  }


}
