package CPP.Absyn; // Java Package generated by the BNF Converter.

public abstract class Id implements java.io.Serializable {
  public abstract <R,A> R accept(Id.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(CPP.Absyn.QCondef p, A arg);

  }

}
