package CPP.Absyn; // Java Package generated by the BNF Converter.

public class QCon extends Stm {
  public final String id_1, id_2;
  public QCon(String p1, String p2) { id_1 = p1; id_2 = p2; }

  public <R,A> R accept(CPP.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof CPP.Absyn.QCon) {
      CPP.Absyn.QCon x = (CPP.Absyn.QCon)o;
      return this.id_1.equals(x.id_1) && this.id_2.equals(x.id_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.id_1.hashCode())+this.id_2.hashCode();
  }


}
