package CPP.Absyn; // Java Package generated by the BNF Converter.

public class QCons extends Def {
  public final ListId listid_1, listid_2;
  public QCons(ListId p1, ListId p2) { listid_1 = p1; listid_2 = p2; }

  public <R,A> R accept(CPP.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof CPP.Absyn.QCons) {
      CPP.Absyn.QCons x = (CPP.Absyn.QCons)o;
      return this.listid_1.equals(x.listid_1) && this.listid_2.equals(x.listid_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listid_1.hashCode())+this.listid_2.hashCode();
  }


}
