package CPP.Absyn; // Java Package generated by the BNF Converter.

public class SDeclUgly2 extends Stm {
  public final Type type_;
  public final String id_1, id_2, id_3, id_4;
  public SDeclUgly2(Type p1, String p2, String p3, String p4, String p5) { type_ = p1; id_1 = p2; id_2 = p3; id_3 = p4; id_4 = p5; }

  public <R,A> R accept(CPP.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof CPP.Absyn.SDeclUgly2) {
      CPP.Absyn.SDeclUgly2 x = (CPP.Absyn.SDeclUgly2)o;
      return this.type_.equals(x.type_) && this.id_1.equals(x.id_1) && this.id_2.equals(x.id_2) && this.id_3.equals(x.id_3) && this.id_4.equals(x.id_4);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(37*(this.type_.hashCode())+this.id_1.hashCode())+this.id_2.hashCode())+this.id_3.hashCode())+this.id_4.hashCode();
  }


}
