package CPP.Absyn; // Java Package generated by the BNF Converter.

public class SDoWhile extends Stm {
  public final Stm stm_;
  public final Exp exp_;
  public SDoWhile(Stm p1, Exp p2) { stm_ = p1; exp_ = p2; }

  public <R,A> R accept(CPP.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof CPP.Absyn.SDoWhile) {
      CPP.Absyn.SDoWhile x = (CPP.Absyn.SDoWhile)o;
      return this.stm_.equals(x.stm_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.stm_.hashCode())+this.exp_.hashCode();
  }


}
