package CPP.Absyn; // Java Package generated by the BNF Converter.

public class SFor extends Stm {
  public final Type type_;
  public final String id_;
  public final Exp exp_1, exp_2, exp_3;
  public final Stm stm_;
  public SFor(Type p1, String p2, Exp p3, Exp p4, Exp p5, Stm p6) { type_ = p1; id_ = p2; exp_1 = p3; exp_2 = p4; exp_3 = p5; stm_ = p6; }

  public <R,A> R accept(CPP.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof CPP.Absyn.SFor) {
      CPP.Absyn.SFor x = (CPP.Absyn.SFor)o;
      return this.type_.equals(x.type_) && this.id_.equals(x.id_) && this.exp_1.equals(x.exp_1) && this.exp_2.equals(x.exp_2) && this.exp_3.equals(x.exp_3) && this.stm_.equals(x.stm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(37*(37*(this.type_.hashCode())+this.id_.hashCode())+this.exp_1.hashCode())+this.exp_2.hashCode())+this.exp_3.hashCode())+this.stm_.hashCode();
  }


}
