package CPP.Absyn; // Java Package generated by the BNF Converter.

public class SIf extends Stm {
  public final Exp exp_;
  public final Stm stm_;
  public SIf(Exp p1, Stm p2) { exp_ = p1; stm_ = p2; }

  public <R,A> R accept(CPP.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof CPP.Absyn.SIf) {
      CPP.Absyn.SIf x = (CPP.Absyn.SIf)o;
      return this.exp_.equals(x.exp_) && this.stm_.equals(x.stm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.exp_.hashCode())+this.stm_.hashCode();
  }


}
