package CPP.Absyn; // Java Package generated by the BNF Converter.

public class SInitsUgly extends Stm {
  public final Type type_;
  public final String id_1, id_2;
  public final Exp exp_1, exp_2;
  public SInitsUgly(Type p1, String p2, Exp p3, String p4, Exp p5) { type_ = p1; id_1 = p2; exp_1 = p3; id_2 = p4; exp_2 = p5; }

  public <R,A> R accept(CPP.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof CPP.Absyn.SInitsUgly) {
      CPP.Absyn.SInitsUgly x = (CPP.Absyn.SInitsUgly)o;
      return this.type_.equals(x.type_) && this.id_1.equals(x.id_1) && this.exp_1.equals(x.exp_1) && this.id_2.equals(x.id_2) && this.exp_2.equals(x.exp_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(37*(this.type_.hashCode())+this.id_1.hashCode())+this.exp_1.hashCode())+this.id_2.hashCode())+this.exp_2.hashCode();
  }


}
