package CPP.Absyn; // Java Package generated by the BNF Converter.

public class Tnameinit1 extends TypeN {
  public final String id_;
  public final Exp exp_;
  public Tnameinit1(String p1, Exp p2) { id_ = p1; exp_ = p2; }

  public <R,A> R accept(CPP.Absyn.TypeN.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof CPP.Absyn.Tnameinit1) {
      CPP.Absyn.Tnameinit1 x = (CPP.Absyn.Tnameinit1)o;
      return this.id_.equals(x.id_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.id_.hashCode())+this.exp_.hashCode();
  }


}
