package CPP.Absyn; // Java Package generated by the BNF Converter.

public class Tvar extends Type {
  public final ListVar listvar_;
  public Tvar(ListVar p1) { listvar_ = p1; }

  public <R,A> R accept(CPP.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof CPP.Absyn.Tvar) {
      CPP.Absyn.Tvar x = (CPP.Absyn.Tvar)o;
      return this.listvar_.equals(x.listvar_);
    }
    return false;
  }

  public int hashCode() {
    return this.listvar_.hashCode();
  }


}
