package CPP.Absyn; // Java Package generated by the BNF Converter.

public abstract class Type implements java.io.Serializable {
  public abstract <R,A> R accept(Type.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(CPP.Absyn.Ttype1 p, A arg);
    public R visit(CPP.Absyn.Ttype2 p, A arg);
    public R visit(CPP.Absyn.Ttype3 p, A arg);
    public R visit(CPP.Absyn.Ttype4 p, A arg);
    public R visit(CPP.Absyn.Tbool p, A arg);
    public R visit(CPP.Absyn.Tdouble p, A arg);
    public R visit(CPP.Absyn.Tint p, A arg);
    public R visit(CPP.Absyn.Tvoid p, A arg);
    public R visit(CPP.Absyn.Tid p, A arg);

  }

}
