package CPP.Absyn; // Java Package generated by the BNF Converter.

public abstract class TypeN implements java.io.Serializable {
  public abstract <R,A> R accept(TypeN.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(CPP.Absyn.Tname1 p, A arg);
    public R visit(CPP.Absyn.Tname2 p, A arg);
    public R visit(CPP.Absyn.Tnameinit1 p, A arg);
    public R visit(CPP.Absyn.Tnameinit2 p, A arg);

  }

}
